# Generated by Django 2.1.5 on 2019-01-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pass', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDriver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpTime', models.DateTimeField()),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isComplete', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_set', to='ridesharing.Prof')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to='ridesharing.Prof')),
                ('sharers', models.ManyToManyField(related_name='sharers_set', to='ridesharing.Prof')),
            ],
            options={
                'verbose_name': 'Ride Info',
                'ordering': ['pickUpTime'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('MINI', 'Minivan'), ('CROSS', 'Crossover')], default='SEDAN', help_text='Vehicle type', max_length=10)),
                ('plateNumber', models.CharField(help_text='8 characters', max_length=8, verbose_name='plateNumber')),
                ('capacity', models.IntegerField(choices=[(4, 4), (6, 6)], default=4)),
            ],
            options={
                'verbose_name': 'Vehicle Info',
            },
        ),
        migrations.AddField(
            model_name='prof',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ridesharing.Vehicle'),
        ),
        migrations.AddField(
            model_name='party',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_party', to='ridesharing.Ride'),
        ),
        migrations.AddField(
            model_name='party',
            name='sharer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharer_party', to='ridesharing.Prof'),
        ),
    ]
