# Generated by Django 2.1.5 on 2019-01-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='canBeShared',
            field=models.BooleanField(default=False),
        ),
    ]
