# Generated by Django 2.1.5 on 2019-01-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0003_ride_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination',
            field=models.CharField(default='', help_text='Please enter a destination', max_length=100),
        ),
    ]
