# Generated by Django 2.1.5 on 2019-02-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0004_ride_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='total_passenger',
            field=models.IntegerField(default=1),
        ),
    ]
