# Generated by Django 2.1.5 on 2019-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0005_ride_total_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='capacity',
            field=models.IntegerField(choices=[(4, 4), (6, 6)], default=4),
        ),
    ]
